### PR TITLE
Use vespa for sorting

### PR DESCRIPTION
**Pull request by olaughter**
Vespa does not allow the use of the order by clause in the grouping, this led to the sorting being done as part of the python post processing instead. Since the first iteration of this code I have managed to find an alternate way of doing grouping sorts within Vespa. This has two advantages, the first is to simplify some of our code, the second is to make queries with sorting on average up to 10% faster

### CODE REVIEW

**Review by THOR300 — APPROVED** [review]
LGTM, potentially an Enum instead of the dict for sort orders if that would make it easier to access and avoid key errors. No strong opinion however.

**Comment by olaughter** [comment]
Thanks @THOR300 I was deliberately avoiding enums because they have some [performance issues](https://github.com/climatepolicyradar/navigator-infra/pull/441) 😞 

Although that link has also just reminded me about literals! I'll take a look and see if I can make this feel a bit better by using them instead

**Comment by THOR300** [comment]
> Thanks @THOR300 I was deliberately avoiding enums because they have some [performance issues](https://docs.pydantic.dev/latest/concepts/performance/#use-literal-not-enum) 😞 
> 
> 
> 
> Although that link has also just reminded me about literals! I'll take a look and see if I can make this feel a bit better by using them instead

Oh no that's no good re enums!

**Comment by olaughter** [comment]
@THOR300 I've decided to leave it as it is for now and will explore improving it as part of [some wider refactoring](https://linear.app/climate-policy-radar/issue/PDCT-965/parameter-handling-needs-deduplicating) that I'm keen to look at next

**Pull request merged**
