### PR TITLE
RND-598  Fix/relax torch dependency

### PR DESCRIPTION
**Pull request by kdutia**
Also bumps version in pyproject.toml. It hadn't been bumped in months – have we been bypassing the check in CI?

### CODE REVIEW

**Review by harrisonpim — APPROVED** [review]
I think this strictness might have originally been introduced by me, months ago! IIRC I was having issues with torch `2.0.1`, and @mpjuhasz pointed me towards [a similar issue that he had previously solved in the metrics repo](https://github.com/climatepolicyradar/metrics/commit/8ae66c322c4ec6479a5dec6e4cdae12f90c8eb99). 

Pinning to `2.0.0` was needlessly strict though, so I'm happy to see this update 😁

**Comment by harrisonpim** [comment]
think this PR also resolves RND-598

**Review by olaughter — APPROVED** [review]
Small thing (and partly just mentioning it for myself), is that the backend currently [pins the specific version of torch](https://github.com/climatepolicyradar/navigator-backend/blob/a8b3f6e79c7252d9109f538651a60e129e65e51c/Dockerfile#29) on build. It's basically a shortcut to use a smaller image. I don't see that as a blocker, but it might need addressing in the future

**Comment by kdutia** [comment]
> think this PR also resolves RND-598
@harrisonpim i was looking for this issue, thanks!

**Pull request merged**
